export { default as RecentAircraft} from './RecentAircraft'
export { default as Header} from './Header'
export { default as Layout} from './Layout'
export { default as Navbar} from './Navbar'
export { default as Slider } from './Slider'
export { default as Footer } from './Footer'
export { default as CommentsForm } from './CommentsForm'
export { default as Search } from './Search'
export { default as TestimonialSlider } from './TestimonialSlider'
export { default as About} from './About'
export { default as RecentNews} from './RecentNews'
export { default as Form} from './Form'